### ISSUE TITLE
Bash install script as daemon

### ISSUE THREAD

**Issue by WatchDogsDev** [pooladkhay/xdp-ip-counter#5]
Is it possible to write a bash script to install the project as a systemd service ?

**Comment by pooladkhay** [comment]
Definitely, You can create a service file named `xdp-ip-counter.service` under `/etc/systemd/system` directory:
```
[Unit]
Description=xdp-ip-counter
After=network.target

[Service]
Type=simple
ExecStart={PATH TO EXECUTABLE} --iface=ens3 --ports=22 --window=20 --serve-ip-list
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
```
Then start and enable it in order to start automatically after a reboot:
```
$ sudo systemctl daemon-reload
$ sudo systemctl start xdp-ip-counter.service
$ sudo systemctl enable xdp-ip-counter.service
```
Make sure to pass the desired flags to the executable. Most importantly, `--iface` should be your network interface name (). passing `-h` will print all possible flags.
